### ISSUE TITLE
Site Security Status - not secure

### ISSUE THREAD

**Issue by VictoriaGuido** [STSILABS/playbook#1]
The pretty version of the site [http://stsilabs.github.io/proposal-guide/](url)

 says it's not secure, at least in chrome. Maybe this can fix it? https[https://help.github.com/en/articles/securing-your-github-pages-site-with-https](url)

**Comment by bengm** [comment]
This was caught in transition... I fixed the link in the readme. Moving to playbook.stsiinc.com and changing this from one repo per topic to one repo that covers mutliple topics (beyond proposals).

**Comment by bengm** [comment]
Updated config and also added a redirect to force https (if you go to http version)
